### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by m2abrams15** [azerg/PackerPE#1]
Hey, hopefully i found the right guy.  im hoping you are the same person responsible for this:

https://coder.pub/2014/10/pe-file-packer-step-by-step-step-12-bugfixes/

i was trying to leave a comment on your site, but it seems to be broken.  So im going to proceed under the assumption that you are the same person.

Anyway, i wanted to say i loved your walk through, i found very informative.  im working now on adding encryption to the packer, to encrypt the original data while its at rest.  my plan was to take the data after line 398:

if(LZO_E_OK !=
            lzo1z_999_compress(reinterpret_cast<const unsigned char*>(packed_sections_info.data()),
            src_length,
            reinterpret_cast<unsigned char*>(&out_buf[0]),
            &out_length,
            work_memory.get())
            )

and then pass that to an AES encryption function.  Then in the unpacker, add in the Decryption functions before it ever tires to uncompress the data .

Have you ever tried this or have any thoughts on it?

**Comment by azerg** [comment]
hey. I'm the wrong guy :sob:
I can just share my thoughts: 
- hope you've checked https://www.cryptopp.com/benchmarks.html, not to use slow version :). 
- i dont see tasks when packed executable have to be so strongly encrypted. Emulator will not try to decrypt it as long as you will have to store key for decryption somewhere anyway.
