### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ghost** [azerg/PackerPE#2]
Hello,I'm sorry my English is terrible.So that I can't express myself enough.If my word is impolite,Please forgive me,thank you

I'm a reverse beginner ,I want to know how to write my own packer,and I want rescue your code ,could you mind to give me the ".sln" file ,Thanks .

I'm so sorry ，I can't express myself.......

**Comment by ghost** [comment]
I'm sorry,I want to say "research",but...not "rescue"
So sorry

**Comment by azerg** [comment]
Except sln file you will need a compiled boost library. So best way will be to get compiled boost, and generate own sln via cmake using existing build.bat ( with your own paths )

**Comment by ghost** [comment]
Thanks！
